server:
  port: 8083
dubbo:
  application:
    name: web_item
  registry:
    address: zookeeper://192.168.98.129:2181
  consumer:
    check: false
spring:
  rabbitmq:
    host: 192.168.98.129
    username: guest
    password: guest
    port: 5672
    virtual-host: /