spring:
  datasource:
    url: jdbc:mysql:///shop1901
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.98.129
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    connection-timeout: 60000

dubbo:
  application:
    name: service_goods
  registry:
    address: zookeeper://192.168.98.129:2181
  protocol:
    name: dubbo
    port: -1
  consumer:
    check: false

mybatis-plus:
  mapper-locations: classpath:com/qf/dao/*.xml
  type-aliases-package: com.qf.entity

